---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: certmanager-production-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@jameslavender.com
    privateKeySecretRef:
      name: le-secret-prod
    solvers:
      - selectors:
        http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: certmanager-staging-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@jameslavender.com
    privateKeySecretRef:
      name: le-secret-staging
    solvers:
      - selector:
        http01:
          ingress:
            class: nginx