---
replicaCount: 3

image:
  repository: jlavend1/jekyll-static-site
  # Overrides the image tag whose default is the chart appVersion.

ingress:
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    cert-manager.io/cluster-issuer: "certmanager-production-issuer"
  }
  hosts:
    - host: kube.jameslavender.com
      paths:
        - path: /
  tls:
     hosts:
       - kube.jameslavender.com

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
